### ISSUE TITLE
route_link() isn't working correctly when app is run from a docker

### ISSUE THREAD

**Issue by maju116** [Appsilon/shiny.router#54] opened 2018-10-29 13:36 UTC
When app is run from docker, url is not copied correctly

**Comment by emilmahler** [comment] 2018-11-04 20:15
This is a problem when you use ShinyProxy (which spins up a docker container with your code) - something goes wrong with the routing. Will they always be incompatible because in ShinyProxy, your code appears in an iframe in the ShinyProxy framework (i.e. routing doesn't make sense, since it'll never appear in the url?). If this is the case, it would still be nice for the code to run anyway.

Openanalytics and Appsilon are making the best Shiny packages right now - I hope they can be made compatible.

**Comment by marekrogala** [comment] 2018-11-05 13:52
@maju116 can you add a repro? (=example how to reproduce this, what would be expected and what is the actual behavior)

**Comment by krystian8207** [comment] 2018-11-07 11:36
Fixed with #57

**Closed by krystian8207** 2018-11-07 11:36 UTC
